name: 'staging-release-update-action'
description: 'update "staging" release'
inputs:
  github-token:
    description: 'github-token'
    required: true
  directory:
    description: 'directory containing artifacts'
    required: true
  tag:
    description: 'update release by tag name'
    required: true
    default: 'staging'
runs:
  using: 'node16'
  main: 'dist/index.js'
